# Site settings
title: Jace Monje
email: jacemonje@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tryhard gamer, web developer, and entrepreneur... among other things. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jacemonje.github.io" # the base hostname & protocol for your site
twitter_username: JACEsec
github_username:  jacemonje

# Build settings
markdown: kramdown
